### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by b4bass** [Bit451/Bit451-Portal#1]
Hey what are you thoughts on rebuilding this with Polymer and angular.js ?

**Comment by Bit451** [comment]
Well, personally I like the idea of sticking with the parent code to the extent possible because ostensibly that means a) less work for us in the short run having to rebuild/test/etc something that's already working, b) less work for us in the long run having to maintain those changes to the code since it stays more in-sync with the parent project (and our improvements can be pulled), c) less time spent rebuilding existing functionality means more time spent building in new functionality, etc.

With that said, any and all alternate approaches are welcome too! The primary goal is to get a (clean/secure/etc) working implementation out for use, so if you do determine that the best route for you is Polymer/Angular, that's totally fine :)

What do you think?

**Comment by b4bass** [comment]
Havent had a chance to look into GreenAdress source code in dept yet.
Actually I was just throwing out some framework that seems promising  to buid the portal, dont even know what GreenAdress is using in the first place.
Though, Google's new Polymer looks fabulous and perfect for a modern HTML5 app.

Please clear this up for me: The portal will display the interface, so it's aims to be something like youtube right?
So, I dont see the point in forking from a bitcoin wallet.
I dont really think the wallet is the core of the app, maybe we should focus on this part after?
Like build the portal, then build the bitcoin implementation on top of that.
Correcting me if i'm wrong but I have trouble to see your "vision".

PS: I've seen the topic on reddit

**Comment by Bit451** [comment]
Yeah, I can understand how the vision might be a bit confusing. I've been meaning to make a UML of how the Portal components and functionality fits together, just haven't had the opportunity to yet.

So, if you think about the foundational structure of sites like YouTube, really the core idea is a social network (account-based site) centered around videos. So, the primary functionality Bit451 has to build from is user accounts. Next, as noted in the [Account Creation / Recovery](http://bit451.org/#account-creation--recovery) section, accounts should be generated like and based on a deterministic wallet, for various reasons. Third, it should be a totally serverless/JS/browser-based solution. Fourth, it should be an active project. And fifth, it should be aesthetic and user-friendly. There are other reasons of course, but these are some of the main ones.

As it turns out, GreenAddress meets all of these requirements. So that is why this solution was chosen. With all that said, yes, it is true that most of the "account-based" functionality is not really crucial until Phase 2. Phase 1 is largely about the ability to stream content from the various File Transfer networks via JS. However, it was important to be able to know things like what frameworks and libraries (ex: angular) would already be available to the content piece from the account "shell" (GreenAddress), and then plug the content player (i.e. JW Player) and Portal Gateways into that in the most logical ways possible.

**Comment by b4bass** [comment]
OK, so I'll be waiting for the UML then :)
Also, I had a little time to checkout greenadress code.
So it's an angular app that uses bitcoin-js lib .

Do you think Google's material design could be a good fit for rebuilding the UI ? (I know it's till in beta)
Haven't had a chance to test Polymer's speed cause I havent got my mac back yet from the store. But I found the angular implementation here : https://github.com/angular/material witch works pretty well on my phone.

**Comment by Bit451** [comment]
Bit451 Portal technology stack:

![Bit451 Portal technology stack](https://raw.githubusercontent.com/Bit451/Bit451/master/uml/bit451-portal-technology-stack.png)

I hope this helps clear up the vision for the Portal, but do let me know if you have further questions about this!

**Comment by Bit451** [comment]
I'm not sure exactly what you mean with regard to "rebuilding the UI". I don't see a need to 'rebuild' the Portal so much as add to (and subtract from) it. I'd be happy to accomplish that using the existing frameworks (i.e. angular) if at all possible. But I may be misunderstanding your question, if so please let me know.
